### ISSUE TITLE
A question about the principle of routing module 

### ISSUE THREAD

**Issue by Aichumei** [UU-Hydro/PCR-GLOBWB_model#52]
Dear author,
I found that the channelStorage of each grid cell is directly contributed by the total runoff. Does this mean that the presence of a river in each grid cell is not important? Because I did not see any code identifying whether there is a river in the grid cell. 
I think that means the routing module doesn't include slope routing concentration calculations，is it reasonable？

**Comment by RensVanBeek** [comment]
Hello,
I believe your question covers two aspects:
1. PCR-GLOBWB is intended to run at relatively coarse spatial scales (> 1 km) and at a daily temporal resolution. This means that the time of concentration is often within the model timestep and all runoff can be assumed to contribute to the channel storage within a single timestep. The underlying assumption -see the documentation- is that every cell is drained by a stream. Thus, we do not identify rivers as such, as every cell has a stream, of which the dimensions need to be specified for the flow equation (in our case, Manning's).
2. So, we do not include hillslope concentration times, if that is what you mean. The bed slope of the river is of course included in the flow equation I mentioned above.

Hope this answers your question.
